import type { Metadata } from "next";
import { App } from "@/src/app";
import { Ysabeau } from "next/font/google";
import "easymde/dist/easymde.min.css";

import { auth } from "@/auth/config";
import { SanityLive } from "@/sanity/lib/live";

import "./globals.css";

const ysabeau = Ysabeau({
  subsets: ["latin", "cyrillic", "symbols"],
  variable: "--font-ysabeau",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log("[root layout.tsx - session]: ", session);

  return (
    <html lang="en">
      <body className={`${ysabeau.variable} font-ysabeau`}>
        <App>{children}</App>
        <SanityLive />
      </body>
    </html>
  );
}
